services:
  drupal:
    build: .
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
    ports:
      - "80:80"
    volumes:
      - ./db:/mnt
      - ./html:/opt/drupal/html

  static:
    build: .
    entrypoint: ["drush", "tome:static"]
    volumes:
      - ./db:/mnt
      - ./html:/opt/drupal/html
    profiles:
      - static
